### ISSUE TITLE
iOS(iPadOS)

### ISSUE THREAD

**Issue by okaits** [FoldingAtHome/fah-client-osx-installer#6]
I want to run folding@home on iPad.

**Comment by PantherX** [comment]
Hiya @okajimaitsuki 

Please note that F@H supports macOS, not iOS. Supporting a new OS is a significant undertaking and it is highly unlikely that it would happen. However, that's up to the developers to decide but please don't hold your breath 😄

**Comment by okaits** [comment]
ok, thanks.
(Sorry for replying/closing after quite a long time.)
